/**
 * Noise, air and heat.
 *
 * The noise model is the one that matters most, because it is the argument the
 * player can hear. Two facts drive it: sound level rises about 3 dB when
 * traffic doubles, and about 9 dB when speed doubles. Slowing a road down does
 * three times as much as emptying it.
 */

import { C } from './constants'
import { crossingDistanceFt, laneMiles, operatingSpeedMph } from './traffic'
import { profileFor } from './landuse'
import type { EnvironmentState, Parcel, StreetState, TrafficState } from './types'

const LOG2 = Math.log10(2)

/**
 * A-weighted equivalent sound level from a traffic stream.
 *
 * Leq = reference + 10*log10(V/V0) + k_speed*log2(S/S0) - k_dist*log2(D/D0)
 *
 * where the speed term is expressed per doubling. At k_speed = 9 dB per
 * doubling this is equivalent to roughly 30*log10(S), which is the standard
 * tyre-noise form.
 */
export function trafficNoiseDba(
  vehiclesPerHour: number, speedMph: number, distanceFt: number,
): number {
  const volume = Math.max(1, vehiclesPerHour)
  // Heavy vehicles are worth about ten cars each.
  const acousticVolume = volume * (1 - C.TRUCK_SHARE) + volume * C.TRUCK_SHARE * C.TRUCK_NOISE_EQUIVALENCE
  const speed = Math.max(5, speedMph)
  const distance = Math.max(10, distanceFt)

  // Each term is expressed per doubling, then converted: log2(x) = log10(x)/log10(2).
  const volumeTerm = C.NOISE_DB_PER_VOLUME_DOUBLING * (Math.log10(acousticVolume / 1000) / LOG2)
  const speedTerm = C.NOISE_DB_PER_SPEED_DOUBLING * (Math.log10(speed / 30) / LOG2)
  const distanceTerm = C.NOISE_DB_PER_DISTANCE_DOUBLING * (Math.log10(distance / 50) / LOG2)

  return C.NOISE_REFERENCE_DBA + volumeTerm + speedTerm - distanceTerm
}

/** Distance from the pavement edge to the centre of the nearest traffic lane. */
export function distanceToNearestLaneFt(street: StreetState): number {
  let offset = street.laneWidthFt / 2
  if (street.onStreetParking !== 'none') offset += 8
  if (street.bikeFacility === 'protected') offset += 9
  else if (street.bikeFacility === 'buffered') offset += 7
  else if (street.bikeFacility === 'painted') offset += 5
  return Math.max(8, offset)
}

/** Share of corridor land under canopy, counting street trees. */
export function canopyFraction(parcels: readonly Parcel[], street: StreetState): number {
  const totalAcres = parcels.reduce((sum, p) => sum + p.acres, 0)
  if (totalAcres === 0) return 0
  const parcelCanopy = parcels.reduce((sum, p) => sum + p.acres * p.canopy, 0)

  // A mature street tree shades roughly 700 sqft.
  const lengthMiles = C.CORRIDOR_LENGTH_FT / 5280
  const trees = street.treesPerMilePerSide * lengthMiles * 2
  const streetCanopyAcres = (trees * 700) / 43560

  const roadAcres = laneMiles(street) * C.ROADWAY_IMPERVIOUS_ACRES_PER_LANE_MILE
  return Math.min(0.85, (parcelCanopy + streetCanopyAcres) / (totalAcres + roadAcres))
}

/** Share of corridor land that sheds water, counting the roadway itself. */
export function imperviousFraction(parcels: readonly Parcel[], street: StreetState): number {
  const totalAcres = parcels.reduce((sum, p) => sum + p.acres, 0)
  const parcelImpervious = parcels.reduce((sum, p) => sum + p.acres * profileFor(p.use).imperviousFraction, 0)
  const roadAcres = laneMiles(street) * C.ROADWAY_IMPERVIOUS_ACRES_PER_LANE_MILE
  if (totalAcres + roadAcres === 0) return 0
  return Math.min(1, (parcelImpervious + roadAcres) / (totalAcres + roadAcres))
}

export function stepEnvironment(
  street: StreetState, parcels: readonly Parcel[], traffic: TrafficState, year: number,
): EnvironmentState {
  // --- Noise ---
  // Tyre noise is generated by vehicles that are MOVING, so the running speed
  // between signals is the right input - not the average trip speed, which is
  // dragged down by vehicles sitting silently at a red light.
  const runningSpeed = operatingSpeedMph(street, parcels)
  const peakHourVolume = traffic.aadt * C.PEAK_HOUR_FACTOR_K
  const kerbDistance = distanceToNearestLaneFt(street)
  let sidewalkNoiseDba = trafficNoiseDba(peakHourVolume, runningSpeed, kerbDistance)
  // Street trees do almost nothing acoustically. Included so the model does
  // not flatter them.
  sidewalkNoiseDba -= Math.min(C.NOISE_VEGETATION_ATTENUATION, street.treesPerMilePerSide / 60)

  const frontage = parcels.filter((p) => p.depth === 0)
  const frontageAcres = frontage.reduce((sum, p) => sum + p.acres, 0)
  const enclosure = frontageAcres > 0
    ? frontage.reduce((sum, p) => sum + profileFor(p.use).frontageQuality * p.acres, 0) / frontageAcres
    : 0

  let setbackNoiseDba = trafficNoiseDba(peakHourVolume, runningSpeed, 100)
  // Buildings held at the pavement shield what is behind them.
  setbackNoiseDba -= enclosure * C.NOISE_BARRIER_ATTENUATION

  // --- Air ---
  const congestionPenalty = 1 + (C.STOP_AND_GO_EMISSION_PENALTY - 1) *
    Math.min(1, Math.max(0, traffic.volumeCapacityRatio))
  const trafficRatio = traffic.aadt / C.INITIAL_AADT
  // PM2.5 barely shows a near-road gradient at all; NO2 shows a real one. The
  // model keeps that asymmetry rather than flattening both into "pollution".
  const pm25Increment = C.PM25_REGIONAL_BACKGROUND * C.PM25_NEAR_ROAD_ELEVATION * trafficRatio * congestionPenalty
  const no2Increment = C.NO2_REGIONAL_BACKGROUND * C.NO2_NEAR_ROAD_ELEVATION * trafficRatio * congestionPenalty

  // --- Heat ---
  const canopy = canopyFraction(parcels, street)
  const impervious = imperviousFraction(parcels, street)

  // Air temperature, not surface temperature. These are different by a factor
  // of five and conflating them is the most common error in this subject.
  const airTempExcessF = Math.max(0,
    C.AIR_TEMP_UHI_MAX_F * impervious ** 1.3 - canopy * 100 * C.AIR_TEMP_COOLING_PER_CANOPY_POINT_F)

  // Surface temperature is where the dramatic numbers live, and it is what a
  // person standing on the pavement in August actually feels.
  const pavedCanopyShare = Math.min(1, canopy * 1.4)
  const shadedExcess = C.SURFACE_TEMP_EXCESS_ASPHALT_F - C.SHADE_SURFACE_TEMP_REDUCTION_F
  const surfaceTempExcessF =
    C.SURFACE_TEMP_EXCESS_ASPHALT_F * (1 - pavedCanopyShare) + shadedExcess * pavedCanopyShare

  const daysOver95 = Math.round(
    C.BASE_DAYS_OVER_95 + C.CLIMATE_DAYS_OVER_95_TREND * year + airTempExcessF * C.DAYS_OVER_95_PER_DEGREE_F)

  return {
    sidewalkNoiseDba: round1(sidewalkNoiseDba),
    setbackNoiseDba: round1(setbackNoiseDba),
    pm25Increment: round2(pm25Increment),
    no2Increment: round2(no2Increment),
    imperviousFraction: round3(impervious),
    canopyFraction: round3(canopy),
    airTempExcessF: round2(airTempExcessF),
    surfaceTempExcessF: round1(surfaceTempExcessF),
    daysOver95,
  }
}

/**
 * The pedestrian's experience of the street, 0 (pleasant) to 1 (hostile).
 * Feeds the walking comfort penalty in the travel model and the audio mix.
 */
export function streetHostility(
  street: StreetState, environment: EnvironmentState, operatingSpeed: number, parcels: readonly Parcel[],
): number {
  const frontage = parcels.filter((p) => p.depth === 0)
  const frontageAcres = frontage.reduce((sum, p) => sum + p.acres, 0)
  const frontageQuality = frontageAcres > 0
    ? frontage.reduce((sum, p) => sum + profileFor(p.use).frontageQuality * p.acres, 0) / frontageAcres
    : 0

  const speedTerm = clamp01((operatingSpeed - 18) / 27)
  const sidewalkTerm = clamp01((7 - street.sidewalkWidthFt) / 5)
  const crossingTerm = clamp01((crossingDistanceFt(street) - 24) / 60)
  const noiseTerm = clamp01((environment.sidewalkNoiseDba - C.NOISE_ANNOYANCE_THRESHOLD) / 18)
  const shadeTerm = clamp01(1 - environment.canopyFraction / 0.35)
  const frontageTerm = clamp01(1 - frontageQuality)
  const spacingTerm = clamp01((street.crossingSpacingFt - 300) / 1100)

  return clamp01(
    0.24 * speedTerm +
    0.13 * sidewalkTerm +
    0.14 * crossingTerm +
    0.13 * noiseTerm +
    0.12 * shadeTerm +
    0.14 * frontageTerm +
    0.10 * spacingTerm,
  )
}

/**
 * Level of Traffic Stress, 1 (a child could ride it) to 4 (nobody will).
 * The single best predictor of whether a bike facility gets used.
 */
export function levelOfTrafficStress(street: StreetState, operatingSpeed: number): number {
  if (street.bikeFacility === 'protected') return operatingSpeed > 40 ? 2 : 1
  if (street.bikeFacility === 'buffered') {
    if (operatingSpeed <= 25) return 2
    return operatingSpeed <= 35 ? 3 : 4
  }
  if (street.bikeFacility === 'painted') {
    if (operatingSpeed <= 25 && street.throughLanesPerDirection <= 1) return 2
    return operatingSpeed <= 35 ? 3 : 4
  }
  // Sharrows and nothing are the same thing to everyone but the person who
  // painted them.
  if (operatingSpeed <= 20 && street.throughLanesPerDirection <= 1) return 2
  return operatingSpeed <= 30 ? 3 : 4
}

function clamp01(x: number): number { return Math.max(0, Math.min(1, x)) }
function round1(x: number): number { return Math.round(x * 10) / 10 }
function round2(x: number): number { return Math.round(x * 100) / 100 }
function round3(x: number): number { return Math.round(x * 1000) / 1000 }
